### ISSUE TITLE
About the web tool

### ISSUE THREAD

**Issue by Clovernana** [CharuKMidha/DIALib-QC#1]
Hi,
thanks for your great job for the quality control of DIA library.I have tried the web tool  but failed to produce any report file.what ‘s the reason for this？

**Comment by CharuKMidha** [comment]
Hi Clovernana, 
Could you please tell me the size of your library? For libraries more than 200 MB please download and use the Linux version of the tool.
Thanks 
Charu

**Comment by Clovernana** [comment]
OK,surely more than 200M. I'll try it in linux. Thank you for your reply.


On 12/9/2020 15:47，CharuKMidha<notifications@github.com> wrote：

Hi Clovernana,
Could you please tell me the size of your library? For libraries more than 200 MB please download and use the Linux version of the tool.
Thanks
Charu
