### ISSUE TITLE
The precursor charge histogram counts the number of fragments rather than the precursors

### ISSUE THREAD

**Issue by fcyu** [CharuKMidha/DIALib-QC#3]
We noticed that the bar height in the precursor charge histogram is from the number of fragments but not precursors. For example, given a precursor with 10 fragments, it counts it 10 rather 1, which seems to be not correct. Could you please fix it?

Thanks,

Fengchao

**Comment by CharuKMidha** [comment]
Hello Fengchao, 

Could please point to the graph which you are referring to? Precursor charge graph is B in the attached pdf and is correct.
[tiny.txt.pdf](https://github.com/CharuKMidha/DIALib-QC/files/14003232/tiny.txt.pdf)

**Comment by fcyu** [comment]
It is B. It is not correct because it counts the charges from the same precursor multiple times (time = number of fragments). Following is a simple demonstration. I used Excel to plot a histogram without collapsing the charges and got the same one as your tool's.

<img width="806" alt="image" src="https://github.com/CharuKMidha/DIALib-QC/assets/6926299/1fe60b4f-ee55-4466-a155-0d686bb630ea">

<img width="617" alt="image" src="https://github.com/CharuKMidha/DIALib-QC/assets/6926299/2a57d783-f57d-4ef6-a420-3a92a654914b">

The correct one should be like the following
<img width="822" alt="image" src="https://github.com/CharuKMidha/DIALib-QC/assets/6926299/3271da37-7494-451f-822c-2a7e47f52c66">

Best,

Fengchao

**Comment by CharuKMidha** [comment]
Okay, got it, it is reporting the precursor_charge based on assays (or fragments). Thanks for finding the bug. I try to fix it.

**Comment by CharuKMidha** [comment]
Can you please check now? I have updated and corrected the DIALib-QC_RPlot.pl. (Instead of plotting pre_z, just needed to plot Distinct_pre_z from fullstats file.)

**Comment by fcyu** [comment]
Yes, it has been fixed in https://github.com/CharuKMidha/DIALib-QC/commit/c1336328afa3cb60b09068377eab67493befb0e6

Thanks,

Fengchao
